defaults: &defaults
  api_keys:
    soundcloud:
      client_key: 33f255a6f2a015cd2bf4c80dc37ebcf7
      client_secret: ef0317165ad0171eb816fbf4546ffaef
  station:
    max_results: 16


development:
  <<: *defaults
  redis:
    host: "localhost"
    port: "6379"
    auth: ""
  node:
    host: "localhost"
    port: "3001"

production:
  <<: *defaults
  redis:
    host: "herring.redistogo.com"
    port: "9992"
    auth: "4bac59599da554c57c02fd3f5236e390"
  node:
    host: "ferris.jit.su"
    port: "80"

