defaults: &defaults
  api_keys:
    soundcloud:
      client_key: 33f255a6f2a015cd2bf4c80dc37ebcf7
      client_secret: ef0317165ad0171eb816fbf4546ffaef

development:
  <<: *defaults

production:
  <<: *defaults

