defaults: &defaults
  api_keys:
    soundcloud:
      client_key: 33f255a6f2a015cd2bf4c80dc37ebcf7
      client_secret: ef0317165ad0171eb816fbf4546ffaef
  station:
    max_results: 10


development:
  <<: *defaults
  redis:
    host: "localhost"
    port: "6379"
    auth: ""
  node:
    host: "localhost"
    port: "3001"

production:
  <<: *defaults
  redis:
    host: "tetra.redistogo.com"
    port: "10062"
    auth: "50647d7d0e670c3f887abc7a14f216bc"
  node:
    host: "ferris.jit.su"
    port: "80"

